using System.Collections.Generic;
using System.Linq;
using Steropes.Tiles.TemplateGenerator.Layout.MatchTypes;
using Steropes.Tiles.TemplateGenerator.Model;

namespace Steropes.Tiles.TemplateGenerator.Layout
{
  public static class MatchTypeStrategyFactory
  {
    static readonly Dictionary<MatcherType, IMatchTypeStrategy> generatorRules;

    static MatchTypeStrategyFactory()
    {
      generatorRules = new Dictionary<MatcherType, IMatchTypeStrategy>
      {
        {MatcherType.CardinalIndex, new CardinalIndexMatchTypeStrategy()},
        {MatcherType.CardinalFlags, new CardinalFlagMatchTypeStrategy()},
        {MatcherType.CellMap, new CellMapMatchTypeStrategy()},
        {MatcherType.Corner, new CornerMatchTypeStrategy()},
        {MatcherType.DiagonalFlags, new DiagonalFlagMatchTypeStrategy()},
        {MatcherType.NeighbourIndex, new NeighbourIndexMatchTypeStrategy()}
      };
    }

    public static IMatchTypeStrategy StrategyFor(MatcherType t)
    {
      if (generatorRules.TryGetValue(t, out var r))
      {
        return r;
      }

      return new BasicMatchTypeStrategy();
    }
  }

  public class GridGenerator
  {
    public void Regenerate(TextureCollection c)
    {
      foreach (var grid in c.Grids)
      {
        if (grid.MatcherType == MatcherType.Basic)
        {
          continue;
        }

        var autoGens = grid.Tiles.Where(t => t.AutoGenerated).ToList();
        foreach (var tile in autoGens)
        {
          grid.Tiles.Remove(tile);
        }
      }

      Generate(c);
    }

    void Generate(TextureCollection c)
    {
      foreach (var grid in c.Grids)
      {
        if (grid.Tiles.Count > 0)
        {
          continue;
        }

        var newTiles = MatchTypeStrategyFactory
          .StrategyFor(grid.MatcherType)
          .Generate(grid);
        grid.Tiles.AddRange(newTiles);
      }
    }
  }
}